### ISSUE TITLE
Remove surrounding whitespace in answers

### ISSUE THREAD

**Issue by hanschen** [David-Kunz/gen.nvim#103]
I get a leading space in the answer from some models, e.g. `mistral` and `mistral-openorca`. This also happens in the terminal:

```
$ ollama run mistral-openorca "hi"
 Hello! How can I help you today?
```

Ultimately I guess this is something that should be fixed in the models/ollama themselves, but in the meanwhile, would it be possible for this plugin to trim surrounding whitespace in the answers? Or could this break code output?

Alternatively, is it possible to solve this using the `extract` property?

**Comment by David-Kunz** [comment]
Hi @hanschen ,

Good catch, I'm afraid this could mess up code generations, hence I'm reluctant to strip the result and rather take it as is. Would it be an option to switch to another model? LLama 3.1 is quite good.

Best regards,
David

**Comment by hanschen** [comment]
Yes, I agree it's difficult to account for all possible cases (I was hoping there might be an easy solution I had overlooked). Better to let them fix it "upstream". I'll test the new Llama 3.1. :)
