### ISSUE TITLE
Add keymap to replace original text

### ISSUE THREAD

**Issue by hanschen** [David-Kunz/gen.nvim#104]
I like to view the response before deciding if I want to replace my original text or not. Would it be possible to include a (configurable) keymap for the response window that replaces the selected text with the generated output?

**Comment by David-Kunz** [comment]
Hi @hanschen ,

That's a great idea! I will implement it!

Best regards,
David

**Comment by David-Kunz** [comment]
Hi @hanschen ,

You can now use `<c-cr>`(configurable with `accept_map`) in the result buffer to replace the previously selected text.

Thanks again for this great suggestion!

Best regards,
David

**Comment by hanschen** [comment]
Awesome, it works great. Many thanks for implementing it so quickly!
