### ISSUE TITLE
Support named registers

### ISSUE THREAD

**Issue by dengzhizhi** [David-Kunz/gen.nvim#107]
This plugin is fantastic!

I was wondering if it would be possible to support named registers (or even more generally, any variable including `@<register>`). This seems like a relatively straightforward enhancement that would greatly expand the flexibility for key mappings. For example I could do something like

`prompt="For the following text, explain {@a} in {@b} and translate the full text, write your answer in {@b}: {@c}"`

```vimL
nnoremap ,ef "ayiw"cyis:let @b="French"<CR>:Gen ExplainWords<CR>
nnoremap ,ek "ayiw"cyis:let @b="Korean"<CR>:Gen ExplainWords<CR>
```

**Comment by David-Kunz** [comment]
Thanks for the suggestion and PR, @dengzhizhi !
