### ISSUE TITLE
ask for diff mode

### ISSUE THREAD

**Issue by ayoubelmhamdi** [David-Kunz/gen.nvim#18]
Vim/Neovim has the best `diff` editor, which is easy to use to display and accept some chunks from a diff between two texts. However, I haven't found any `plugin` in `Neovim` that provides me with the generated text from `ChatGPT` in a diff format.

**Comment by David-Kunz** [comment]
Hi @ayoubelmhamdi ,

Thank you for this interesting suggestion! The way I usually work is to just apply the generated output and use e.g. my git integration to show me the differences, in case I need to see it.

https://github.com/lewis6991/gitsigns.nvim

What do you think?

Thank you again and best regards,
David

**Comment by David-Kunz** [comment]
Hi @ayoubelmhamdi ,

After thinking a bit more about this feature, I decided to not integrate it into `gen.nvim`. I want to keep it as a minimal plugin.
To see the diff, you can commit your project to git and use other plugins to show the diff, e.g. https://github.com/sindrets/diffview.nvim or https://github.com/lewis6991/gitsigns.nvim.

Best regards,
David

**Comment by ayoubelmhamdi** [comment]
That's accepted, i will try to get the same diff that this clone of `vscode` provide it (cursor)[https://cursor.sh/]

![image](https://github.com/David-Kunz/gen.nvim/assets/34358145/4a9d9ecc-fb9e-4b49-af73-9135c37e5821)

### Submit:

![image](https://github.com/David-Kunz/gen.nvim/assets/34358145/43e56fbb-a9e0-4eac-9a29-72593fcb6c32)
