### ISSUE TITLE
Fix code with help of LSP

### ISSUE THREAD

**Issue by pratikgajjar** [David-Kunz/gen.nvim#19]
Thank you for building this plugin and sharing with the community. 

Prompt : Write code in golang to send email with attachment. handle content type automatically. 

Improvement:
- We can pass all errors generated by lsp and send it back to gen ai when asked to fix the code. 

<img width="1512" alt="image" src="https://github.com/David-Kunz/gen.nvim/assets/10096516/6d9c96f4-dee0-4086-abc0-5ea14a4920c0">

**Comment by David-Kunz** [comment]
Hi @pratikgajjar ,

That's an interesting idea! After obtaining the list of all LSP errors/warnings, one could either annotate the provided text or shift the respective lines (which are relative to the whole document).

In any way, I'd need to see if the current models are capable of making use of such annotations.

Thank you again and best regards,
David

**Comment by pratikgajjar** [comment]
Hi @David-Kunz 
  Appreciate your response. One more possibility is that LSP itself become LLM aware and pass error data to LLM for suggested fix. Like how we can sort import and fix minor errors by LSP they can do the same. Here benefit would be that no one needs to make their Code Editor smart and improvements done over LSP gets benefited by everyone. 

Shall I close this issue as it's not really an issue ?

**Comment by David-Kunz** [comment]
Hi @pratikgajjar ,

Yes, I'd say we close this issue. First, I'll try to make this plugin as simple and lean as possible, without too much code. 

Thank you and best regards,
David
