### ISSUE TITLE
error in readme

### ISSUE THREAD

**Issue by JoseConseco** [David-Kunz/gen.nvim#2]
Following code from readme:
```lua
table.insert(require('gen').prompts, {
    Elaborate_Text = {
        prompt = "Elaborate the following text:\n$text",
        replace = true
    },
    Fix_Code = {
        prompt = "Fix the following code. Only ouput the result in format ```$filetype\n...\n```:\n```$filetype\n$text\n```",
        replace = true,
        extract = "```$filetype\n(.-)```"
    }
})
```

Will give wrong structure in prompts table like this:
 `prompts = { old_prompt={}, old_prompt2={},   {inserted_promp1={}, inserted_prompt2={}}`
Which then gives error when running :Gen. 
what worked was 
require('gen').prompts['my custom prompt'] = { ... }

**Comment by David-Kunz** [comment]
Thank you again, @JoseConseco , it's fixed now!
