### ISSUE TITLE
Option to enable word wrap?

### ISSUE THREAD

**Issue by fredrikaverpil** [David-Kunz/gen.nvim#25]
Hi and thanks for this excellent plugin!

I noticed that the output of e.g. `:Gen Summarize` can produce one very long line:

![image](https://github.com/David-Kunz/gen.nvim/assets/994357/a114e0aa-ff84-4a72-92ba-74576fa4df5a)

If I manually enabled word wrap, it becomes much more readable:

![image](https://github.com/David-Kunz/gen.nvim/assets/994357/490d4393-caa4-47a4-ba44-168b97780ad6)

I think I would prefer to have this word wrapping "always on". Do you think it's possible to add an option to enable this?

```lua
-- lazy.nvim example
{
"David-Kunz/gen.nvim",
config = function()
  require("gen").setup({
    word_wrap = true
  })
end,
},

```

**Comment by David-Kunz** [comment]
Hi @fredrikaverpil ,

Thanks for this suggestion.

[This PR](https://github.com/David-Kunz/gen.nvim/pull/26) allows to set the [window config](https://neovim.io/doc/user/api.html#api-win_config) via

```lua
require('gen').win_config = { ... }
```

but it's not yet possible to modify the buffer options... let me think how to support this in the most generic way.

Best regards,
David

**Comment by samharju** [comment]
As the output buffer is detected as filetype=markdown, I tried setting wrap on in `ftplugin/markdown.lua`. It works fine if I first open some markdown file, but not if the first markdown is opened by gen. Maybe a distinct filetype would help with this, or figuring out why ftplugin is not triggered by gen?

**Comment by kjjuno** [comment]
This PR should fix this issue

https://github.com/David-Kunz/gen.nvim/pull/36

**Comment by David-Kunz** [comment]
Should be fixed!

**Comment by rensftw** [comment]
Hey!

I can see this issue again in 9804316
I have an ftplugin for markdown with the following settings:
```lua
vim.opt_local.wrap = true
vim.opt_local.linebreak = true
vim.opt_local.breakindent = true 
vim.opt_local.showbreak = '⋮ ' 
```


These settings get applied when I open any Markdown file, but not in the markdown buffer that `:Gen` creates
https://github.com/David-Kunz/gen.nvim/assets/22574186/993f466e-6039-411a-b7b4-4d4dbc0570e3
