### ISSUE TITLE
hard to add this plugin using lazy.nvim with the container option setting.

### ISSUE THREAD

**Issue by meicale** [David-Kunz/gen.nvim#29]
I need to use the docker container to serve my custom model and it works when using ollama docker images. BUT, when come to using it in this  plugin, it is difficult to set up the container value in lazy.nvim package manager. Can you provide more code snips to using different config setting ups? Thanks for your time and effort on time good project.

**Comment by meicale** [comment]
It should be just as simple as this and it helps the beginner to start：
```
{ 
    "David-Kunz/gen.nvim",
    config = function()
      require('gen').container = 'ollama_gpu'
      -- require('gen').model = 'zephyr'
    end,
  },
```

**Comment by David-Kunz** [comment]
Hi @wishuuu ,

Could you help this user? Shouldn't it be enough to set the `container` property? I must admit, I haven't tested it yet.

**Comment by wishuuu** [comment]
Hi @meicale !

 Here is code snippet from my lazy config:
 `return {
    "David-Kunz/gen.nvim",
    config = function()
        vim.keymap.set('v', '<leader>gn', ':Gen<CR>')
        vim.keymap.set('n', '<leader>gn', ':Gen<CR>')
        require('gen').model = 'codellama'
        require('gen').container = 'ollama'
    end
}`

Honestly it's hard to tell what may be wrong with your config. Can you check if `docker exec ollama_gpu ollama run zephyr TEST` returns any error in your case? Also are you using Linux or Windows?

**Comment by kjjuno** [comment]
There is now a traditional setup function. Does that resolve this issue?

**Comment by David-Kunz** [comment]
Hi @meicale ,

The docker option was removed since we switched to HTTP-based communication.
You should be able to specify the `init` function to start your docker container and use port forwarding to communicate with it.

Best regards,
David
