### ISSUE TITLE
Cannot override model

### ISSUE THREAD

**Issue by JoseConseco** [David-Kunz/gen.nvim#3]
I think this is due to  line
```
    local opts = vim.tbl_deep_extend('force', {
        model = 'mistral:instruct',
        command = M.command
```
Not sure though.  I do not see anywhere require('gen').model = 'your_model'  - model seems to be set only in   local opts. And not in M.model...

**Comment by David-Kunz** [comment]
Thank you @JoseConseco , it's fixed now!
