### ISSUE TITLE
Gen.nvim don't work

### ISSUE THREAD

**Issue by yesiddev** [David-Kunz/gen.nvim#35]
Hi, when I try to use gen, the plugin doesn't generate anything:
<img width="1725" alt="image" src="https://github.com/David-Kunz/gen.nvim/assets/53379076/256251f9-2472-4940-b05e-9e57d9ac67be">

I have installed ollama and mistral:instruct

<img width="940" alt="image" src="https://github.com/David-Kunz/gen.nvim/assets/53379076/fbe28ce6-00ab-49b4-942c-ba35612c3959">

I am using lazy to install it and this is my config to gen.nvim
```
return {
	"David-Kunz/gen.nvim",
	config = function()
		require("gen").prompts["DevOps me!"] = {
			prompt = "You Are a senior devops engineer, acting as an assistant. You offer help with cloud technologies like: Terraform, AWS, Kubernetes, Python, Azure DevOps yaml pipelines. You answer with code examples when possible. $input:\n$text",
			replace = true,
		}

		vim.keymap.set("v", "<leader>]", ":Gen<CR>")
		vim.keymap.set("n", "<leader>]", ":Gen<CR>")
	end,
}
```

I am using and MacBook pro m2 with Ventura 13.6

**Comment by ch-tactica** [comment]
I'm afraid I'm having the same problem after a restart, tried ollama serve

**Comment by yesiddev** [comment]
@ch-tactica  Thanks for share the issue channel, I temporarily resolved it downgrading the ollama version and thanks for your observation about the change in the output of ollama.
