### ISSUE TITLE
Prompt wont work in it has quote in it

### ISSUE THREAD

**Issue by JoseConseco** [David-Kunz/gen.nvim#4]
eg. this wont work 
-  Add 'aa_' prefix to module names
I think they should be escaped for command line  with \` ?

**Comment by David-Kunz** [comment]
Seems to work for me, which OS do you use?
<img width="1080" alt="Screenshot 2023-10-02 at 09 10 05" src="https://github.com/David-Kunz/gen.nvim/assets/1009936/dc19cfe8-64e7-43b8-898a-80e474c3118b">

**Comment by David-Kunz** [comment]
Note: `'` characters [are already escaped](https://github.com/David-Kunz/gen.nvim/blob/474fb07ef11d125885ca36baf314db81ce7c2e6c/lua/gen/init.lua#L92).

This is the resulting command:
```
ollama run mistral 'Summarize the following text:
Add \'aa_\' prefix to module names
I think they should be escaped for command line with ` ?'
```

**Comment by David-Kunz** [comment]
Did you maybe override `require('gen').command` since [you couldn't set the model](https://github.com/David-Kunz/gen.nvim/issues/3)?

**Comment by alaaibrahim** [comment]
Ok, did some debugging on this, as this is happening with me too.

The issue is in escaping the `'` character, for shell it needs to be `'\''`

see `:h shellescape`

the fix is pretty simple, I can open a pr for it
```
        text = string.gsub(text, "'", "'\\''")
```

**Comment by sch-28** [comment]
I still have this issue for some reason 🤔 

this is a 'test' - works
this is a `test` - works
this is a "test" - doesn't work

**Comment by DanielEliasib** [comment]
i have this issue too, also happening with double quotes, for example calling `:Gen Review_Code` on the following input:
```
"test"
```
generates the following query:
```
curl --silent --no-buffer -X POST http://localhost:11434/api/generate -d "{""model"": ""zephyr"", ""stream"": true, ""prompt"": ""Review the following code and make concise suggestions:\n```cpp\n\""test\""\n```""}"
```
but calling it with the code:
```
'test'
```
generates:
```
curl --silent --no-buffer -X POST http://localhost:11434/api/generate -d "{""model"": ""zephyr"", ""stream"": true, ""prompt"": ""Review the following code and make concise suggestions:\n```cpp\n'test'\n```""}"
```
my OS is windows

**Comment by alaaibrahim** [comment]
Unfortunately I don't have a windows machine to test, but just ran the same tests above, and both works

Input: `"test"`
command

```
curl --silent --no-buffer -X POST http://localhost:11434/api/generate -d '{"model": "codellama", "stream": true, "prompt": "Review the following code and make concise suggestions:\n```cpp\n\"test\"\n```"}' 
```

Input: `'test'`
command

```
curl --silent --no-buffer -X POST http://localhost:11434/api/generate -d '{"model": "codellama", "stream": true, "prompt": "Review the following code and make concise suggestions:\n```cpp\n'\''test'\''\n```"}'
```

Although cannot say for sure, but it might be that neovim doesn't recognize your shell that you are using, or it's mis-configured somewhere.
see
 `help 'shell'`
`help 'shellquote'`
and `help 'shellxquote'`

**Comment by DanielEliasib** [comment]
it seems to be a windows only problem, it has to do with the fact that the commands are being called with cmd so [`vim.fn.shellescape()`](https://neovim.io/doc/user/builtin.html#shellescape()) has to substitute every double quote with *two* double quotes, but `vim.fn.json_encode()` already tries to escape double quotes like `\"`.

so when the command is called the json is all messed up and doesn't have consistent escaping.

i think I've already fixed it on my end, I'll open a PR.
