### ISSUE TITLE
Ctrl-c or Esc doesn't kill the job and so there is no way to stop the prompt without closing vim or waiting till its over.

### ISSUE THREAD

**Issue by JulesHauchecorne** [David-Kunz/gen.nvim#40]

**Comment by David-Kunz** [comment]
Thank you @JulesHauchecorne , I'll look into it once https://github.com/David-Kunz/gen.nvim/pull/36 is merged (which changes quite a few things).

**Comment by David-Kunz** [comment]
Hi @JulesHauchecorne ,

With the newest version, once the window is closed, the job will be destroyed.

Best regards,
David

**Comment by JulesHauchecorne** [comment]
Amazing Thank you!!
