### ISSUE TITLE
Lost functionality with output rendered with "termopen"

### ISSUE THREAD

**Issue by leafo** [David-Kunz/gen.nvim#41]
A few things I noticed from the [`termopen` change](https://github.com/David-Kunz/gen.nvim/commit/501fe1f7ef801efa26e9c446ba58ab51e8cfedf7) with regards to usability:

* pressing any key will now immediately close the window, this means:
  * You can now longer scroll up and down the output if it's longer than the size of the window
  * You can no longer make selections in the window to copy data from it
* stderr is now included the output (not as critical, but can be an annoyance if using alternate command that outputs debug info)

The change was originally discussed here: https://github.com/David-Kunz/gen.nvim/issues/32#issuecomment-1819531258

**Comment by leafo** [comment]
Few more things I noticed:

* Output from the command is hard wrapped, meaning if generated text wraps due to outputting a line longer than the width of the window and is then inserted back into the file being edited (or is copied), there will be a newline character where the wrap happened
* Interacting with the window with the mouse will convert it to a mode that can then be scrolled and selected with the keyboard (perhaps this can point us towards a solution with regards to having it close on keypress)

**Comment by David-Kunz** [comment]
Hi @leafo ,

Thank you for writing this down, I also noticed (some of) these downsides in my daily usage. That was the reason I originally didn't use `termopen`, but `ollama` changed their behaviour, so we had to (temporarily) switch back to it.

With https://github.com/David-Kunz/gen.nvim/issues/39 the former behaviour should be restored, I hope we can merge it this weekend.

Best regards,
David

**Comment by David-Kunz** [comment]
Hi @leafo ,

We removed `termopen`, hence closing this issue.

Thanks again for reporting!
