### ISSUE TITLE
Suggestion: add choice of models to switch to

### ISSUE THREAD

**Issue by kapral18** [David-Kunz/gen.nvim#43]
Not entirely sure where to put tho can be added in the main list of actions that is invoked with :Gen 

or can be added to just README as a suggestion for people to use if they want to conveniently switch
to different models for a given :Gen invocation. What do you think?

this is how I use it for myself:

```lua
local changeModel = function()
  -- take the first column of the output of ollama list after header row and trim whitespace
  -- so that systemlist returns a valid list of models
  local list = vim.fn.systemlist("ollama list | awk 'NR>1' | cut -f1 | tr -d ' '")

  vim.ui.select(list, { prompt = "Select a model: " }, function(selected)
    if selected == nil then
      return
    end

    require("gen").model = selected
    print("Model set to " .. selected)
  end)
end

return {
  "David-Kunz/gen.nvim",
  keys = {
    { "<leader>ai", ":Gen<CR>", mode = { "n", "v", "x" }, desc = "Local [AI]: Menu" },
    { "<leader>am", changeModel, mode = { "n" }, desc = "Local [AI]: Change Model" },
  },
  opts = {
    display_mode = "float",
    show_model = true,
    no_serve = true,
    debugCommand = true,
  },
}
```

**Comment by kapral18** [comment]
@David-Kunz  I see the [commit](https://github.com/David-Kunz/gen.nvim/commit/99e5cfcfb7603098b270066bc190b16ec2cea810), epic thank you!

**Comment by David-Kunz** [comment]
Hi @kapral18 ,

Thanks for the suggestion and code, I've implemented it in https://github.com/David-Kunz/gen.nvim/pull/44

Best regards,
David

**Comment by David-Kunz** [comment]
Ha, you were faster 😄
