### ISSUE TITLE
Using Plugged as package manager?

### ISSUE THREAD

**Issue by zevv** [David-Kunz/gen.nvim#51]
I'm loading Gen using 

```
Plug 'David-Kunz/gen.nvim', {'branch': 'main'}                           
```

What's the proper way to pass the configuration in this case?

Thanks.

**Comment by David-Kunz** [comment]
Hi @zevv ,

You can just use

```lua
require('gen').setup({...})
```

**Comment by zevv** [comment]
Yes, thanks for that - my wrong for not properly reading the docs!
