### ISSUE TITLE
Text outside the floating windows

### ISSUE THREAD

**Issue by micheleavellaNUT** [David-Kunz/gen.nvim#53]
Hi, I'm new to nvim and I am currently using the Gen plugin. Recently, I noticed an issue when using the AI (Mistral) inside nvim. When the answer provided by the AI is long and fits onto a single line, it goes beyond the boundaries of the floating window. Does anyone have any advice on how to resolve this issue?

Additionally, I was wondering if it is possible to customize the size and position of the floating windows.

![2023-12-15_19-11](https://github.com/David-Kunz/gen.nvim/assets/128721937/a600cbaf-5308-44db-8d2e-3baf7c4e54ec)

**Comment by David-Kunz** [comment]
Hi @micheleavellaNUT ,

What should happen is that at the end of the line, the text will continue in the new line.
Example:
<img width="864" alt="Screenshot 2023-12-17 at 10 14 05" src="https://github.com/David-Kunz/gen.nvim/assets/1009936/d253387a-0dd3-464f-9b85-1a49b00570b2">

There's the unofficial config option `win_config`, but I might remove it in the future. You can also use vertical splits with `display_mode = 'split'`.

**Comment by Joseph-D-Bradshaw** [comment]
I didn't used to suffer from this, but I got it on a new machine where I also setup neovim from scratch. I think it would be helpful to see a config to compare @micheleavellaNUT as I have an old working config in the git history of my dotfiles. I might be able to find out why

**Comment by dathinaios** [comment]
@David-Kunz I am having the same problem.. Just so I don't create a whole issue to ask a question: I changed to "split". Any easy way to use a horizontal split so that the text appears at the bottom? 

Thank for the plugin by the way! 🙂

**Comment by iFrostizz** [comment]
This happens if you don't set the `:set wrap` option, the text is going to overflow the buffer.
It might be good to default to this option for windows opened by gen (or add it as a configuration ?).

**Comment by David-Kunz** [comment]
Hi @iFrostizz ,

Thanks, this is already done by `nvim.gen`:

```lua
        vim.api.nvim_win_set_option(M.float_win, "wrap", true)
```

**Comment by paulobazooka** [comment]
Thank you for your help, I had the same problem and noticed that I had set it not to break lines.

**Comment by Joseph-D-Bradshaw** [comment]
I do not get wrapping unless I explicitly call `:set wrap` when the floating window is open. I am on the latest commit (87fbe81).

Extremely minimal configuration:

```
  -- Minimal configuration
  {
    "David-Kunz/gen.nvim",
    opts = {
      model = "deepseek-coder:6.7b",
  },
```

I know this is not a problem with gen.nvim but likely my own setup, how to debug it I am hoping one of the other commenters might be able to provide if they solved their issue - this doesn't happen with `display_mode = "split"` so I know it is a floating window specific issue.
