### ISSUE TITLE
feat: opt in to default prompts

### ISSUE THREAD

**Issue by tjex** [David-Kunz/gen.nvim#64]
I'd like to make a PR that implements the option for users to opt in/out of the default prompts. 

Would look like this: 

```lua
require("gen").setup({ load_default_prompts = bool })
```

Use case: 

The default prompts can be "hidden" for users who do not want to use them, or want to modify them into their own version that they use instead of the original defaults.

Users who are content with only the default prompts, or adding a few of their own to compliment them will see no change.

**Comment by David-Kunz** [comment]
Hi @tjex ,

Thank you for this suggestion. Users are already in full control of the prompts, to overwrite the default ones, they can do

```lua
require('gen').prompts = {}
```

and add their own ones.

Would that work for you?

Thank you and best regards,
David

**Comment by tjex** [comment]
hahaha truuuuuuue. Talk about (me) over complicating things 😅
This works for me for sure.
