### ISSUE TITLE
No output if the model is missing

### ISSUE THREAD

**Issue by Mte90** [David-Kunz/gen.nvim#71]
I am on linux and I installed Ollama (and I see running).

When I try the `:Gen` command anything generate a tiny window empty:
![immagine](https://github.com/David-Kunz/gen.nvim/assets/403283/6b0f999e-0e37-4e25-8eaf-3733b4c783ac)

I was able also to generate a big window inside the code but I see if the cursor is on the Neotree buffer open inside that.
There isn't any parameter to define what filetype/buffer exclude.

**Comment by Mte90** [comment]
So the readme doesn't mention to install the ollama model but there isn't any report for the error:
![immagine](https://github.com/David-Kunz/gen.nvim/assets/403283/45ba2959-a9da-4b68-a181-85bedb8b4563)

**Comment by Mte90** [comment]
Now works but the window is very tiny:

![immagine](https://github.com/David-Kunz/gen.nvim/assets/403283/8dfc6cee-5618-4246-b670-c7968fd398db)

**Comment by David-Kunz** [comment]
Hi @Mte90 ,

Thank you for checking.

I will check if we can make errors more apparent. Regarding the issue with the window: The window size depends on your current window, in your screenshot, could you kindly check if the window is bigger if you invoke it from the right split?

Thanks and best regards,
David

**Comment by Mte90** [comment]
So I tried running nvim direct to a file and not opening the the neotree sidebar.
I am getting the same issue.

Looking at the code https://github.com/David-Kunz/gen.nvim/blob/85a739cea06148a56d52f26b01d63de6671ce4ce/lua/gen/init.lua#L137 it is a different buffer compraed to the one with the code.
On my tests it is `7` but the code is on `1` and doesn't have a filetype. Maybe ggets confused with the output window?
