### ISSUE TITLE
Improve markdown rendering

### ISSUE THREAD

**Issue by Mte90** [David-Kunz/gen.nvim#77]
In my case the markdown is not rendered, there is something I have to configure for that?
![immagine](https://github.com/David-Kunz/gen.nvim/assets/403283/e75db8c8-1186-4cc3-bf19-b1317492668f)

**Comment by David-Kunz** [comment]
Hi @Mte90 ,

The file type of the buffer is set to markdown. Do you have the corresponding Tree-Sitter parser? What happens if you open a markdown file, is it rendered correctly?

**Comment by Mte90** [comment]
It seems that works
