### ISSUE TITLE
How to close the modal window?

### ISSUE THREAD

**Issue by Mte90** [David-Kunz/gen.nvim#78]
Also if I run `:q` is still there but empty.

**Comment by Kahitar** [comment]
For me it's just pressing the 'q' key when the modal is in focus.

**Comment by Mte90** [comment]
In my case doesn't work

**Comment by David-Kunz** [comment]
Hi @Mte90 ,

This is a just a normal window, so `:q` should close it. There's also the `q` shortcut. I wonder why both of them won't work in your case, do you have any other plugins installed which might interfere?

**Comment by Mte90** [comment]
So a `:q` close the content but the buffer is still there.

![image](https://github.com/David-Kunz/gen.nvim/assets/403283/37f6ef25-74bc-46a7-aa27-c6cd91e7dd19)

My mapping is on https://github.com/mte90/dotfiles/blob/master/.config/nvim/lua/mappings.lua

I think that the only mapping involved is this:
```
-- Close buffer with no window changes, it is executed also on empty buffers
vim.api.nvim_command("cnoreabbrev <expr> q getcmdtype() == ':' && getcmdline() == 'q' ? 'Bdelete' : 'q'")
```
I have to try it without that.

**Comment by Mte90** [comment]
So without that rule `:q` works but not just `q`
