### ISSUE TITLE
Possible cmp integration

### ISSUE THREAD

**Issue by JoseConseco** [David-Kunz/gen.nvim#8]
Is there any chance for cmp integration ?  I saw [this video](https://www.youtube.com/watch?v=gAsYolNrjtQ) tutorial about  making sources for cmp.   It would require special mode with inline completion suport eg. this one https://huggingface.co/TheBloke/CodeLlama-13B-Instruct-GGML - support infilling. 
I may try to  code this with some help

**Comment by David-Kunz** [comment]
Hi @JoseConseco ,

Great suggestion! I think code completion requires a lot of work, especially in determining the right context. There is [this project](https://github.com/FarisHijazi/PrivateGitHubCopilot) for VSCode. It uses the same CoPilot extension, but uses a local LLM as a backend. Maybe something similar can be achieved in Neovim, too.

**Comment by David-Kunz** [comment]
Hi @JoseConseco ,

After more consideration I decided to not enable a `cmp` integration, I'll leave this to more specialized plugins. I keep this plugin as minimal as possible.

Best regards,
David
