### ISSUE TITLE
`$text` only grab a single character into prompt

### ISSUE THREAD

**Issue by gzfrozen** [David-Kunz/gen.nvim#84]
While Select any amount of text (both in v and V mode), use prompt contains `$text` to generate, there seems to be only one character is grabbed into the prompt. 

In the following example, it seems only `,` is send to the prompt.
<img width="1277" alt="image" src="https://github.com/David-Kunz/gen.nvim/assets/39619255/d3375542-7b97-47de-a6d2-0e3246d583d9">

The prompt I am using:
```
prompt = "Explain the meaning of following code:\n```$filetype\n$text\n```",
```

**Comment by David-Kunz** [comment]
Hi @gzfrozen ,

Thanks for reporting, do you have an example?

How do you select the text, with v or V?

**Comment by gzfrozen** [comment]
@David-Kunz 
I tried both v select and V select, single line and multiple lines. But all seem to only grab the character under the final cursor's place.

**Comment by David-Kunz** [comment]
Thank you @gzfrozen , it works for me. Are you using the newest version?

**Comment by gzfrozen** [comment]
@David-Kunz 
Yes.  I started to use this plugin yesterday so I think it"s the newest version.

**Comment by gzfrozen** [comment]
@David-Kunz 
https://github.com/gzfrozen/gen.nvim/commit/8e1999ef97a4a41f9d95888fc9b8677cc296094c

I tried to debug this by print out the grabbed content, and it seems to grab only 1 character: 
<img width="135" alt="image" src="https://github.com/David-Kunz/gen.nvim/assets/39619255/b4bb40e2-ff40-4f02-8934-0bcfda6c4e62">

**Comment by David-Kunz** [comment]
Thank you, @gzfrozen , could you update the plugin? Yesterday there have been many changes. Thank you!

**Comment by gzfrozen** [comment]
@David-Kunz 
I updated to the latest version (46ab810). And it is still unfixed.

**Comment by David-Kunz** [comment]
Thank you, @gzfrozen .

Could you try it with the following keymap?

```lua
vim.keymap.set({ 'n', 'v' }, '<leader>]', ':Gen<CR>')
```

then select some text (e.g. with shift-v) and trigger the command.

So far, I could not reproduce your issue.

**Comment by gzfrozen** [comment]
> Thank you, @gzfrozen .
> 
> Could you try it with the following keymap?
> 
> ```lua
> vim.keymap.set({ 'n', 'v' }, '<leader>]', ':Gen<CR>')
> ```
> 
> then select some text (e.g. with shift-v) and trigger the command.
> 
> So far, I could not reproduce your issue.

@David-Kunz 
Wow, that fix my problem. 

My key binding target command was `<cmd>Gen<GR>`, and it failed.
After I change it to `:Gen<GR>` and the problem is fixed.

I'm new to vim and don't know the difference between `<cmd>` and `:`, so there is a difference I guess.

**Comment by David-Kunz** [comment]
Thanks for confirming, @gzfrozen !
