### ISSUE TITLE
[Question] Option to show nothing and just replace the selected text

### ISSUE THREAD

**Issue by muhammad-saleh** [David-Kunz/gen.nvim#92]
I have a use case where I want to have a shortcut to fix/complete code for me. I want to just press the shortcut and have the selected text replaced with the output from gen.nvim/model.

Is there an option to do that? I think this would be a new display mode?

**Comment by David-Kunz** [comment]
Hi @muhammad-saleh ,

If the prompt has the option `replace = true`, it will replace the selected text. Do you want to hide the generation process?

**Comment by muhammad-saleh** [comment]
@David-Kunz yes correct.

**Comment by zhuzy-2018** [comment]
![image](https://github.com/David-Kunz/gen.nvim/assets/42018599/c44b25ad-4cbf-42c3-9ecc-fafc1198b407)
I also want this feature, like the extension "continue" in vscode, use gray as suggest complete code. Then all I have to do is press "Tab" to accept it.

**Comment by David-Kunz** [comment]
Hi @muhammad-saleh ,

You can now use the option `hidden` to not show any generation window at all. It will automatically set the prompt to `replace = true`.

Best regards,
David
