### ISSUE TITLE
[Question] Access the whole buffer/file content

### ISSUE THREAD

**Issue by muhammad-saleh** [David-Kunz/gen.nvim#93]
I want to improve the suggestions that I get by providing the current open buffer code to the model, in a hope that the model will have more context and hence provide better suggestions.

How can I do that in a custom prompt? I only see $register but it's for yanked text and not the whole buffer.

**Comment by David-Kunz** [comment]
Hi @muhammad-saleh , you can highlight the whole buffer (`ggVG`) and then invoke `gen.nvim`, would that be enough?

**Comment by muhammad-saleh** [comment]
@David-Kunz It would be great if this happens automatically in the background.

**Comment by David-Kunz** [comment]
I could take the whole buffer if nothing is selected... will have a look!

**Comment by David-Kunz** [comment]
Hi @muhammad-saleh ,

I modified the behaviour: If no text is selected, the text of the whole buffer is used.

Now, you can e.g. call `:Gen Ask` with prompt `what's that?` and get an answer of the current buffer.

Thanks for the suggestion and best regards,
David
