### ISSUE TITLE
Bring back `generate` support endpoint

### ISSUE THREAD

**Issue by Altiire** [David-Kunz/gen.nvim#97]
As stated in https://github.com/David-Kunz/gen.nvim/pull/68, the `chat` endpoint is now used and the `generate` endpoint is not usable anymore.

IMO, supporting both (multiple) endpoints should be a preferable option

**Comment by David-Kunz** [comment]
Hi @Altiire ,

What advantage does the `generate` endpoint have?

Thanks and best regards,
David

**Comment by Altiire** [comment]
Hello @David-Kunz ,

The generate endpoint allows to setup the system (see options here: https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-completion)

With the current chat endpoint only supported, I have created many models just to edit the system... :/

Regards,

**Comment by David-Kunz** [comment]
Hi @Altiire ,

Would it also work for you to loop over all your prompts (`require('gen').prompts`) and prepend the system message?
